### ISSUE TITLE
Things Done and Need to do 

### ISSUE THREAD

**Issue by Sayanti86** [UBC-MDS/image-compression-toolkit--R#4]
Hello , 
Merged the Pull request .
I have added R test cases for Compress referring Python. 
I have created empty function for crop , it was adding warning while I was building the test cases .
DESCRIPTION had some issue , (GOD knows why ) , fixed it .
Created PULL Request. 

Next things : 
Both have a look .
Both give acknowledgement that no more updates required from your side , THEN I will create Releases .

**Comment by aldenchen** [comment]
Also need to add a file for crop function
